### ISSUE TITLE
No such file or directory: '/etc/dgl/hostfile'

### ISSUE THREAD

**Issue by leepengcheng** [Qihoo360/dgl-operator#15]
>deploy  examples/v1alpha1/GraphSAGE_dist.yaml:

### error of dgl-graphsage-launcher pod
```shell
Phase 3/5: dispatch partitions
----------
Traceback (most recent call last):
File "tools/dispatch.py", line 102, in 
main()
File "tools/dispatch.py", line 44, in main
with open(args.ip_config) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/dgl/hostfile'
----------
Phase 3/5 error raised
```

### error of dgl-operator pod
```shell
021-08-14T09:45:48.716Z	INFO	controllers.DGLJob	Finished reconciling job	{"dgljob": "dgl-operator/dgl-graphsage", "dgl-operator/dgl-graphsage": "80.81µs"}
2021-08-14T09:45:48.722Z	ERROR	controllers.DGLJob	unable to fetch DGLJob	{"dgljob": "dgl-operator/dgl-graphsage", "error": "DGLJob.qihoo.net \"dgl-graphsage\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
github.com/Qihoo360/dgl-operator/controllers.(*DGLJobReconciler).Reconcile
/workspace/controllers/dgljob_controller.go:115
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:297
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:252
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:215
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:99
```

**Comment by ryantd** [comment]
@leepengcheng  Sorry for the late reply. Would you like to provide more info, like
1. Did `dgl-graphsage-partitioner` Pod work as expected? And the final status was `Completed`?
2. Please provide `dgl-graphsage-partitioner` Pod log.
3. Did `dgl-graphsage-worker` Pods create at first as expected, but failed or evicted before the main container of `dgl-graphsage-launcher` running?

The regular lifecycle is like
1. Partitioning phase
    1. `dgl-graphsage-partitioner` Pod has a `running` status, which means the main container of the Pod is running.
    2. A initContainter (partitioning finish tracker) of `dgl-graphsage-launcher` is running.
2. Partitioning finished
    1. `dgl-graphsage-partitioner` Pod has a `completed` status.
    2. The initContainter (partitioning workload tracker) is completed.
    3. `dgl-graphsage-worker` Pods are intended to be created.
    4. A initContainter (worker readiness tracker) of `dgl-graphsage-launcher` is running.
3. Training phase
    1. `dgl-graphsage-launcher` Pod has a `running` status, which means the main container of the Pod is running.
    2. All `dgl-graphsage-worker` Pods have a `running` status.
    3. Launching the distributed training...

**Comment by leepengcheng** [comment]
@ryantd 

i solve this problem by  'time.sleep(10)'，because the partitioner pod finished too quickly(i mouted local cora dataset)😱

**Comment by allendred** [comment]
> leepengcheng

请问是怎么挂载数据的,我现在通过nfs挂载数据和代码,在partitioner节点找不到,怎么在partitioner节点挂载呢

**Comment by leepengcheng** [comment]
> > leepengcheng
> 
> 请问是怎么挂载数据的,我现在通过nfs挂载数据和代码,在partitioner节点找不到,怎么在partitioner节点挂载呢

```yaml
apiVersion: qihoo.net/v1alpha1
kind: DGLJob
metadata:
  name: dgl-graphsage
  namespace: dgl-operator
spec:
  partitionMode: DGL-API
  cleanPodPolicy: Running
  dglReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: k3d-sfai-registry:39203/examples:graphsage-dist
            name: dgl-graphsage
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                ephemeral-storage: 10Gi
              limits:
                ephemeral-storage: 15Gi
            command:
            - dglrun
            args:
            - --graph-name
            - graphsage
            # partition
            - --partition-entry-point
            - code/load_and_partition_graph.py
            - --num-partitions
            - "2"
            - --balance-train
            - --balance-edges
            - --dataset-url
            - http://snap.stanford.edu/ogb/data/nodeproppred/products.zip
            # training
            - --train-entry-point
            - code/train_dist.py
            - --num-epochs
            - "1"
            - --batch-size
            - "1000"
            - --num-trainers
            - "1"
            - --num-samplers
            - "4"
            - --num-servers
            - "1"
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: k3d-sfai-registry:39203/examples:graphsage-dist
            name: dgl-graphsage
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                memory: 15Gi
                cpu: "2"
                ephemeral-storage: 10Gi
              limits:
                memory: 20Gi
                cpu: "4"
                ephemeral-storage: 15Gi
            volumeMounts:
              - mountPath: /root/.dgl/ogbn_products
                name: ogbn
              - mountPath: /dgl_workspace/code
                name: code

          volumes:
          - name: ogbn
            hostPath:
              path: /home/dgl/data/ogbn_products
              type: Directory
          - name: code
            hostPath:
              path: /home/dgl/dgl/examples/GraphSAGE_dist/code
              type: Directory
```
你可以参考一下，我用的K3S搭的，所以要挂载两次，注意宿主机的文件路径和容器内部的路径的差别
